### PR TITLE
Phoebe - Spotify API Data Access Object Implementation

### PR DESCRIPTION
**Pull request by ShihHsin0723**
- Completed the implementation of the SpotifyAPIDataAccessObject
- Removed the API authorization methods from the class to align with the Single Responsibility Principle
- One of the core methods implemented is getTrackIds() which gets all tracks' IDs from the specified playlist and the access token. 
- The other core method is storePlaylistInfo(), which stores playlist information in the playlists csv file by getting all the playlist attributes from private helper methods. 

Concerns:
- Where should we obtain the authentication code after the user is redirected to the authorization link?

Updates:
- storePlaylistInfo() method is now in FilePlaylistsDataAccessObject, which deals merely with the playlists csv file.

### CODE REVIEW

**Review by oliviaw12 — APPROVED** [review]
Hi Phoebe! I find your code to be very organized and easy to follow. One thing I noticed is that in your getTracksArtistsTitles, you store the artists found in a playlist in an ArrayList. But, since an artist may appear multiple times in a user's playlist, do you think that using a hash map may be more useful and efficient as then we can store key-value mappings between an artist and the number of times that artist appears in the playlist?

**Comment by ShihHsin0723** [comment]
Thank you Olivia for your code review! It's a great point that an artist may appear multiple times in the ArrayList and storing this kind of data using a hash map is indeed more efficient as we don't need to loop through the whole ArrayLists to compare our data.

**Comment by ShihHsin0723** [comment]
I added getGenres method and modified the return type of getTracksTitleArtists() method and deleted the helper method ArrayListToHashMap as we convert the data types in other methods directly.

**Review by zfjuliana — COMMENTED** [review]
Hi Phoebe! Overall, I think your Spotify API data access object file has a neat structure and contains the relevant endpoints for our program. I noticed your informative comments throughout the code, and I think that you could transform them into javadoc for the public methods. This would be helpful especially since some of the methods are more difficult to understand. One suggestion I have is that it may be more coherent to refactor the code for obtaining the access token into a separate class since they are separate API endpoints. This way, the program can better adhere to the Single Responsibility Principle.

**Comment by ShihHsin0723** [comment]
Hi Juliana! Thank you for your suggestion. I agree that I should put the code for obtaining the access token into a separate file as it involves a significant amount of logic and has its own set of concerns (handling token expiration, refreshing tokens).

**Pull request merged**
